### ISSUE TITLE
Docker line added when creating a flow through Terraform

### ISSUE THREAD

**Issue by PilarIH** [kestra-io/terraform-provider-kestra#118]
### Expected Behavior

When the flow is created through the UI, you can build it only with these parameters:

```
id: get_connections
namespace: prod
tasks:
- id: hello
  type: io.kestra.plugin.scripts.python.Script
  script: | <here comes the python code>
```

### Actual Behaviour

When you create the flow from Terraform, the UI shows this code:

```
id: get_connections
namespace: prod
tasks:
- id: hello
  type: io.kestra.plugin.scripts.python.Script
  docker:
    pullPolicy: ALWAYS
  script: |
```

The docker and pullPolicy are added by default and since there's no image specified, it raises an error when checking the flow in the UI. The docs say nothing about docker being a required parameter and it definitely works without it.

### Steps To Reproduce

Create a Kestra Flow resource through Terraform with a Python script task, apply Terraform and check the UI to see the result.

### Environment Information

- Kestra Version: 0.16.1
- Operating System (OS / Docker / Kubernetes): OS
- Java Version (If not docker):
