### ISSUE TITLE
terraformed flow with powerbi task: waitDuration is converted to float

### ISSUE THREAD

**Issue by jeremycopinlm** [kestra-io/terraform-provider-kestra#72]
### Expected Behavior

When we use io.kestra.plugin.powerbi.RefreshGroupDataset task
waitDuration value should stay with original ISO_8601 format and not be converted to a float

### Actual Behaviour

`waitDuration: PT5M` is changed to `waitDuration: 300.0` when we look at the flow on the UI

### Steps To Reproduce

Create a flow with terraform and look at the source on the UI

### Environment Information

- Kestra Version: 0.7.1
- Provider Version: 0.7.0

### Example flow

```
id: refresh_powerbi
namespace: some.namespace
tasks:
- id: refresh
  type: io.kestra.plugin.powerbi.RefreshGroupDataset
  tenantId: "{{ secret('powerbi_tenant_id') }}"
  clientId: "{{ secret('powerbi_client_id') }}"
  clientSecret: "{{ secret('powerbi_client_secret') }}"
  groupId: "{{ secret('powerbi_group_id') }}"
  datasetId: "fqsldsqldnqskj"
  wait: true
  waitDuration: PT5M
```
